### ISSUE TITLE
RTSP for Wyze Cam v3 Pan?

### ISSUE THREAD

**Issue by TheCableGuy99** [Lukejb14/Wyze-RTSP#3]
Hi,

Is there any RTSP firmware for the Wyze Cam v3 Pan?

Thanks.

**Comment by Lukejb14** [comment]
I currently use Wyze Cam Pan v3 via RSTP using Scrypted.

RTSP is supported for all Wyze cameras with Scrypted:
https://docs.scrypted.app/add-camera.html

Additionally, Wyze Docker Bridge supports some camera models too.
Check compatibility: 
https://github.com/mrlt8/docker-wyze-bridge?tab=readme-ov-file#supported-cameras

Both Available in Home Assistant as an addon.
