### ISSUE TITLE
is the firmware still working anymore? I can't get the light turn solid

### ISSUE THREAD

**Issue by guocity** [Lukejb14/Wyze-RTSP#4]
is the firmware still working anymore? I can't get the light turn solid,
I tried both v2, and v3 camera, seems like holding the setup only end up "ready to connect"

**Comment by DecoRobotics** [comment]
Are you holding the setup button while it is plugged in?

**Comment by AbsoluteComputers** [comment]
Having the same issue. I am holding down the setup button. It just seems to reset the camera and kicks it off the app. If I abandon the set up the app has dropped the connection. Tried multiple times. New Camera and its set up on app easily.

**Comment by ipoletti** [comment]
Try downgrading first to firmware 4.9.9.1472 using the same procedure
https://support.wyze.com/hc/en-us/articles/360024852172
https://s3.us-west-2.amazonaws.com/download.wyzecam.com/firmware/v2/demo_4.9.9.1472.bin.zip

Then I was able to flash the rtsp firmware ok.

**Comment by MyCodeRocks** [comment]
Interesting I have a Wyze Pan v2 - I have tried to downgrade my firmware (used different SD cards as well) - tried to downgrade to :
[4.49.1.47](https://download.wyzecam.com/firmware/panV2/recovery_wcpv2_4.49.1.47.zip) (March 17, 2022)
[4.49.1.41](https://s3.us-west-2.amazonaws.com/download.wyzecam.com/firmware/panV2/recovery_wcpv2_4.49.1.41.zip) (February 17, 2022)

No matter what I try (different SD cards FAT32) power off, hold setup button, add power. Orange light stays on for about 10secs then it goes to flashing between orange and blue and just goes back into normal operation. 

Doesnt seem like its allowing the downgrade of the firmware. They must of blocked it?

**Comment by rallyrabbit** [comment]
Like I said in the other thread, this is old firmware.  I think Wyze changed their bootloaders with one of the upgrades that would prevent downgrades.  I found some evidence to support this in their SW release notes.

**Comment by cdaringe** [comment]
Just tried with a v3 as well. Seems like we may be stuck.

Their docs suggest this is feasible still, as of April 2023. See https://support.wyze.com/hc/en-us/articles/360031490871-How-to-flash-your-Wyze-Cam-firmware-manually

Nonetheless, I failed to succeed. Tried looking thru the bin on a hex editor too, trying to find a version number in there. Probably could give it more of a deeper go--we could try fiddling with that, seeing if we can find a bypass.

**Comment by Lukejb14** [comment]
RTSP is supported for all Wyze cameras with Scrypted:
https://docs.scrypted.app/add-camera.html

Additionally, Wyze Docker Bridge supports some camera models too.
Check compatibility: 
https://github.com/mrlt8/docker-wyze-bridge?tab=readme-ov-file#supported-cameras

Both Available in Home Assistant as an addon.
