### ISSUE TITLE
Wyze Pan CAM V2

### ISSUE THREAD

**Issue by MyCodeRocks** [Lukejb14/Wyze-RTSP#6]
Is there any firmware for RTSP for the Wyze Pan Cam V2?

**Comment by rallyrabbit** [comment]
Other than what's here, no.  This is extremely old firmware and Wyze has had slight hardware revisions and boot loader changes too that might prevent this from working.  I only have a few Wyze Cam v1 left that will take this.  I switched to Reolink for everything else.

**Comment by MyCodeRocks** [comment]
Thank you for the quick response!! - Its a pitty cause I cant get [Xiaomi-Dafang-Hacks](https://github.com/McNutnut/Xiaomi-Dafang-Hacks) - working either.

I managed to downgrade the software - but only after enabling Cam Plus (so the downgrade seems to be behind some pay wall).

I managed to downgrade to the earliest available on the site, but they block everything else. Pity we cant use RTSP on these cameras.

**Comment by MyCodeRocks** [comment]
So some further info for those checking in on the Wyze Pan Cam V2 - recent HW updates have now changed the T20 to T31(HL_PAN2) - so I doubt the FW versions available will work for rtsp.

**Comment by Lukejb14** [comment]
RTSP is supported for all Wyze cameras with Scrypted:
https://docs.scrypted.app/add-camera.html

Additionally, Wyze Docker Bridge supports some camera models too.
Check compatibility: 
https://github.com/mrlt8/docker-wyze-bridge?tab=readme-ov-file#supported-cameras

Both Available in Home Assistant as an addon.
