### ISSUE TITLE
ANy news on RTSP for Wyze Cam v3 Pro?

### ISSUE THREAD

**Issue by DanielBendersky** [Lukejb14/Wyze-RTSP#9]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DanielBendersky** [comment]
Any news on RTSP for Wyze Cam v3 Pro? I have some new cameras and will like to configure them inside a Synology NAS, so I need the RTSP feature enabled.

**Comment by Lukejb14** [comment]
RTSP is supported for v3 Pro with Wyze Docker Bridge:mrlt8/docker-wyze-bridge: WebRTC/RTSP/RTMP/LL-HLS bridge for Wyze cams in a docker containergithub.comAvailable for Home Assistant as an addon.On Jun 21, 2024, at 12:05 PM, Daniel Bendersky ***@***.***> wrote:﻿
Any news on RTSP for Wyze Cam v3 Pro? I have some new cameras and will like to configure them inside a Synology NAS, so I need the RTSP feature enabled.
